export { anonymizeTenantId, anonymizeThreatValue, anonymizePattern } from "./intelligence/anonymizer";
export type { AnonymizedSignalType } from "./intelligence/anonymizer";
export { threatNetwork, ThreatNetwork } from "./intelligence/threatNetwork";
export type { GlobalThreatFeed, SharedThreatSignal } from "./intelligence/threatNetwork";
export { detectGlobalCampaigns } from "./intelligence/campaignDetector";
export type { GlobalCampaign } from "./intelligence/campaignDetector";
export { correlateGlobalThreats } from "./intelligence/globalCorrelationEngine";
export type { GlobalCorrelationResult } from "./intelligence/globalCorrelationEngine";
export { buildBroadcastAlerts } from "./intelligence/broadcastEngine";
export type { GlobalThreatAlert } from "./intelligence/broadcastEngine";
export { calculateGlobalThreatScore, globalSeverityLabel } from "./intelligence/globalThreatScoring";
export { canShareThreatSignal, getThreatSharingSettings, setThreatSharingSettings } from "./intelligence/tenantThreatSharingSettings";
export type { TenantThreatSharingSettings } from "./intelligence/tenantThreatSharingSettings";

export { defenseCoordinator, DefenseCoordinator } from "./defense/defenseCoordinator";
export type { GlobalDefenseFeed } from "./defense/defenseCoordinator";
export type { DefenseActionType, DefensePosture, DefenseRecommendation, DefenseScope, EarlyWarning, WarningLevel } from "./defense/defenseModels";
export { defenseRecommendationEngine, DefenseRecommendationEngine } from "./defense/defenseRecommendationEngine";
export { defensePropagationEngine, DefensePropagationEngine } from "./defense/defensePropagationEngine";
export type { PropagatedDefenseRecommendation } from "./defense/defensePropagationEngine";
export { buildGlobalDefenseMap } from "./defense/globalDefenseMap";
export type { GlobalDefenseMap, GlobalDefenseMapRegion } from "./defense/globalDefenseMap";
export { getTenantDefensePosture, listDefensePostures, postureSeverityModifier, setTenantDefensePosture } from "./defense/defensePostureSync";
export { earlyWarningEngine, EarlyWarningEngine } from "./defense/earlyWarningEngine";
export { prioritizeGlobalDefense } from "./defense/globalDefensePrioritizer";
export { defenseAuditLogger, DefenseAuditLogger } from "./defense/defenseAudit";
export type { DefenseAuditEvent, DefenseAuditEventType } from "./defense/defenseAudit";

export { socWarGameEngine, SOCWarGameEngine } from "./simulation/socWarGameEngine";
export type { SOCWarGameSnapshot } from "./simulation/socWarGameEngine";
export type { AttackSimulationResult, DefenseSimulationResult, SimulationScenario, SOCGap, SOCEvolutionPoint, SOCResilienceScore, WarGameReport, WarGameRun } from "./simulation/simulationModels";
export { scenarioGenerator, ScenarioGenerator } from "./simulation/scenarioGenerator";
export { attackSimulationEngine, AttackSimulationEngine } from "./simulation/attackSimulationEngine";
export { defenseSimulationEngine, DefenseSimulationEngine } from "./simulation/defenseSimulationEngine";
export { socResilienceScorer, SOCResilienceScorer } from "./simulation/socResilienceScorer";
export { gapDetectionEngine, GapDetectionEngine } from "./simulation/gapDetectionEngine";
export { continuousSimulationScheduler, ContinuousSimulationScheduler } from "./simulation/continuousSimulationScheduler";
export { warGameReportEngine, WarGameReportEngine } from "./simulation/warGameReportEngine";
export { rankSimulatedThreats } from "./simulation/simulatedThreatRanking";
export type { SimulatedThreatRank } from "./simulation/simulatedThreatRanking";
export { socEvolutionTracker, SOCEvolutionTracker } from "./simulation/socEvolutionTracker";

export { socEvolutionEngine, SOCEvolutionEngine } from "./evolution/socEvolutionEngine";
export type { SOCEvolutionAdjustment, SOCEvolutionMetrics, SOCEvolutionState, SOCDriftStatus, SOCVersionedConfig } from "./evolution/evolutionModels";
export { defaultEvolutionState, applySingleAdjustment } from "./evolution/evolutionAdjuster";
export { detectSOCDrift } from "./evolution/socDriftDetector";
export { recommendedAdjustmentFromSimulation } from "./evolution/simulationLearningEngine";
export { rollbackToStable } from "./evolution/evolutionRollbackEngine";
export { limitedResponseEngine, LimitedResponseEngine } from "./autonomous/limitedResponseEngine";
export type { AutomationLevel, AutonomousActionRecord, AutonomousActionStatus } from "./autonomous/autonomousModels";
export { automationLevelFor, shouldExecute } from "./autonomous/executionDecisionEngine";
export { requiresHumanApproval } from "./autonomous/approvalGate";
export { validateAction } from "./autonomous/actionValidator";
export { rollbackAction } from "./autonomous/actionRollbackEngine";
export { autonomousAuditLogger, AutonomousAuditLogger } from "./autonomous/autonomousAuditLogger";
