import { Download, FileText, ShieldCheck } from "lucide-react";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, RiskBadge, Section } from "@/components/base";
import { correlateIoc } from "@/domain/ioc/correlationEngine";
import { buildPdfReadyReport, exportCsv, exportJson } from "@/domain/export/exporters";

const result = correlateIoc("login-banco-validacao.net");
const apiList = ["VirusTotal", "Shodan", "GreyNoise", "AbuseIPDB", "AlienVault", "Censys"];

export function PDFReportGenerator() {
  const report = buildPdfReadyReport({ score: result.riskScore, ioc: result.query, timeline: result.timeline, apis: apiList, threatIntelligence: result.relationships, mitre: ["T1566", "T1583"], conclusion: "Indicador requer contenção e monitoramento." });
  const json = exportJson(report);
  const csv = exportCsv(result.relationships.map((item) => ({ value: item.value, type: item.type, source: item.source, confidence: item.confidence })));
  return <div className="space-y-6"><Section title="PDF Report Generator" description="Relatório profissional preparado para exportação em PDF, JSON e CSV." action={<div className="flex gap-2"><Button variant="secondary"><Download />JSON</Button><Button variant="secondary"><Download />CSV</Button><Button><FileText />PDF</Button></div>} /><Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5 text-cyan-300" />Shield Threat Report</CardTitle></CardHeader><CardContent><div className="mx-auto max-w-4xl rounded-lg border border-slate-800 bg-slate-950/70 p-6"><div className="flex items-center justify-between border-b border-slate-800 pb-4"><div><p className="text-2xl font-bold text-slate-50">Shield Security Scanner</p><p className="text-sm text-slate-500">Enterprise Threat Intelligence Report</p></div><RiskBadge level={result.severity}>Score {result.riskScore}</RiskBadge></div><div className="mt-6 grid gap-4 md:grid-cols-2"><div><p className="text-xs uppercase tracking-[0.14em] text-slate-500">IOC</p><p className="mt-1 font-mono text-slate-100">{result.query}</p></div><div><p className="text-xs uppercase tracking-[0.14em] text-slate-500">APIs utilizadas</p><div className="mt-2 flex flex-wrap gap-2">{apiList.map((api) => <Badge key={api} tone="neutral">{api}</Badge>)}</div></div></div><div className="mt-6 grid gap-3">{result.timeline.map((item) => <div key={item.id} className="rounded-lg border border-slate-800 p-3"><p className="font-semibold text-slate-100">{item.timestamp} · {item.title}</p><p className="text-sm text-slate-500">{item.detail}</p></div>)}</div><div className="mt-6 rounded-lg border border-slate-800 bg-slate-900/50 p-4"><p className="font-semibold text-slate-100">Conclusão</p><p className="mt-1 text-sm text-slate-400">O indicador apresenta risco operacional e deve ser bloqueado em controles preventivos enquanto investigação adicional é conduzida.</p></div></div><details className="mt-4 text-xs text-slate-500"><summary>Preview JSON/CSV</summary><pre className="mt-2 max-h-40 overflow-auto rounded bg-slate-950 p-3">{json.slice(0, 900)}\n\n{csv}</pre></details></CardContent></Card></div>;
}
