export { socAutonomousEngine, SOCAutonomousEngine } from "./core/socAutonomousEngine";
export type { AutonomousDecisionInput } from "./core/socAutonomousEngine";
export { socAutoRemediationEngine, SOCAutoRemediationEngine } from "./remediation/socAutoRemediationEngine";
export type { RemediationPlan, RemediationType } from "./remediation/socAutoRemediationEngine";
export { socSOARWorkflowEngine, SOCSOARWorkflowEngine } from "./workflows/socSOARWorkflowEngine";
export type { SOARWorkflowRule } from "./workflows/socSOARWorkflowEngine";
export { evaluateSOCActionApproval } from "./gates/socActionApprovalGate";
export type { ApprovalDecision } from "./gates/socActionApprovalGate";
export { socAutoResponsePipeline, SOCAutoResponsePipeline } from "./pipeline/socAutoResponsePipeline";
export { socAutoEscalationEngine, SOCAutoEscalationEngine } from "./escalation/socAutoEscalationEngine";
export { socThreatContainmentEngine, SOCThreatContainmentEngine } from "./containment/socThreatContainmentEngine";
export { socOutcomeLearningEngine, SOCOutcomeLearningEngine } from "./learning/socOutcomeLearningEngine";
export type { SOCLearningSignal } from "./learning/socOutcomeLearningEngine";
export { getSOCAutonomousMode, setSOCAutonomousMode, canAutoExecuteSafeActions, describeSOCAutonomousMode } from "./mode/socAutonomousModeController";
export type { SOCAutonomousMode } from "./mode/socAutonomousModeController";
export { socSOARAuditLogger, SOCSOARAuditLogger } from "./audit/socSOARAuditLogger";
export type { SOARAuditEvent } from "./audit/socSOARAuditLogger";

export { socSafeRemediationEngine, SOCSafeRemediationEngine } from "./remediation/socSafeRemediationEngine";
export type { SafeRemediationInput, SafeRemediationOutput } from "./remediation/socSafeRemediationEngine";
export { socRemediationDecisionEngine, SOCRemediationDecisionEngine } from "./decision/socRemediationDecisionEngine";
export type { RemediationDecision, RemediationDecisionInput } from "./decision/socRemediationDecisionEngine";
export { evaluateCloudActionGate, getCloudActionPolicy } from "./gates/socCloudActionGate";
export type { CloudActionGateDecision } from "./gates/socCloudActionGate";
export { socHumanApprovalEngine, SOCHumanApprovalEngine } from "./human/socHumanApprovalEngine";
export type { HumanApprovalRecord } from "./human/socHumanApprovalEngine";
export { remediationStateMachine, RemediationStateMachine } from "./remediation/remediationStateMachine";
export type { RemediationState, RemediationStateRecord } from "./remediation/remediationStateMachine";
export { socRollbackEngine, SOCRollbackEngine } from "./remediation/socRollbackEngine";
export type { RollbackRecord } from "./remediation/socRollbackEngine";
export { evaluateGlobalSafetyRules, getGlobalSafetyCooldowns } from "./safety/socGlobalSafetyRules";
export { cloudExecutionAuditLogger, CloudExecutionAuditLogger } from "./audit/cloudExecutionAuditLogger";
export type { CloudExecutionAuditEvent } from "./audit/cloudExecutionAuditLogger";
export type { RemediationActionRequest, RemediationActionResult, RemediationActionType, RemediationRiskLevel, RemediationExecutionStatus } from "./remediation/remediationTypes";

export { socSelfHealingEngine, SOCSelfHealingEngine } from "./self-healing/socSelfHealingEngine";
export type { SelfHealingRunResult } from "./self-healing/socSelfHealingEngine";
export { systemStateMonitor, SystemStateMonitor } from "./self-healing/systemStateMonitor";
export { autoRepairEngine, AutoRepairEngine } from "./self-healing/autoRepairEngine";
export { healingLoopController, HealingLoopController } from "./self-healing/healingLoopController";
export { configTuningEngine, ConfigTuningEngine } from "./self-healing/configTuningEngine";
export { intelligentRollbackEngine, IntelligentRollbackEngine } from "./self-healing/intelligentRollbackEngine";
export { socBehaviorLearningEngine, SOCBehaviorLearningEngine } from "./self-healing/socBehaviorLearningEngine";
export { guardParameter, guardConfig, getParameterBounds } from "./self-healing/safeParameterGuard";
export { healingDecisionEngine, HealingDecisionEngine } from "./self-healing/healingDecisionEngine";
export { recoveryModeEngine, RecoveryModeEngine } from "./self-healing/recoveryModeEngine";
export { healingAuditLogger, HealingAuditLogger } from "./self-healing/healingAuditLogger";
export { evaluateSelfHealingSafety, selfHealingSafetyPolicy } from "./self-healing/selfHealingSafetyRules";
export { simulateHealingImpact } from "./self-healing/healingImpactSimulator";
export type { HealingAuditEvent, HealingChange, HealingConfigState, HealingDecision, HealingImpactSimulation, SOCSystemState, SystemStateSnapshot, TunableParameter } from "./self-healing/selfHealingTypes";

export { globalExecutionLock, GlobalExecutionLock } from "./locks/globalExecutionLock";
export { doubleExecutionGuard, DoubleExecutionGuard, executionFingerprint } from "./remediation/doubleExecutionGuard";
export { activateFailsafeMode, clearFailsafeMode, getFailsafeMode } from "./safety/socGlobalSafetyRules";
